In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [3]:
data = pd.read_csv('PlayTennis.csv')
data.head()

    Outlook Temperature Humidity    Wind Play Tennis
0     Sunny         Hot     High    Weak          No
1     Sunny         Hot     High  Strong          No
2  Overcast         Hot     High    Weak         Yes
3      Rain        Mild     High    Weak         Yes
4      Rain        Cool   Normal    Weak         Yes

In [9]:
from sklearn.preprocessing import OrdinalEncoder
outlook_encoder = OrdinalEncoder()
data['Outlook'] = outlook_encoder.fit_transform(data[['Outlook']])
temperature_encoder = OrdinalEncoder()
data['Temperature'] = temperature_encoder.fit_transform(data[['Temperature']])
humidity_encoder = OrdinalEncoder()
data['Humidity'] = humidity_encoder.fit_transform(data[['Humidity']])
windy_encoder = OrdinalEncoder()
data['Wind'] = windy_encoder.fit_transform(data[['Wind']])
PlayTennis_encoder = OrdinalEncoder()
data['Play Tennis'] = PlayTennis_encoder.fit_transform(data[['Play Tennis']])

In [10]:
data

    Outlook  Temperature  Humidity  Wind  Play Tennis
0       2.0          1.0       0.0   1.0          0.0
1       2.0          1.0       0.0   0.0          0.0
2       0.0          1.0       0.0   1.0          1.0
3       1.0          2.0       0.0   1.0          1.0
4       1.0          0.0       1.0   1.0          1.0
5       1.0          0.0       1.0   0.0          0.0
6       0.0          0.0       1.0   0.0          1.0
7       2.0          2.0       0.0   1.0          0.0
8       2.0          0.0       1.0   1.0          1.0
9       1.0          2.0       1.0   1.0          1.0
10      2.0          2.0       1.0   0.0          1.0
11      0.0          2.0       0.0   0.0          1.0
12      0.0          1.0       1.0   1.0          1.0
13      1.0          2.0       0.0   0.0          0.0